### ISSUE TITLE
Cannot terminate quarkus app with CTRL + C when hazelcast client is failing to connect to cluster.

### ISSUE THREAD

**Issue by obbyK** [hazelcast/quarkus-hazelcast-client#47] opened 2020-07-06 04:14 UTC
**Describe the bug**
When the client is trying and failing to connect to cluster (since there is no hazelcast running on the machine/network), you cannot stop the quarkus application with CTRL + C. Nothing happens. The application continues to run. The application jar is an uber jar.

**Expected behavior**
The app should terminate.

**To Reproduce**
[Here ](https://github.com/obbyK/hazelcast-quarkus-test) is a simple reproducer. Run `mvn clean package`, then `java -jar target\hazelcast-test-runner.jar`. 
The code contains a simple scheduler that tries to get a map and add an entry every 5s.
Hazelcast should not be running on the machine/network.

**Additional context**
Tested on windows 10 (1903) with Git Bash (2.27.0.windows.1), Powershell (7.0.2) and CMD.
I am not sure if this is an issue with quarkus itself or this extension.

**Comment by pivovarit** [comment] 2020-07-07 20:28
I confirm that I managed to reproduce the issue. Will have a deeper look tomorrow

**Comment by pivovarit** [comment] 2020-07-13 21:02
This seems like an issue with Quarkus itself. Looks like an app can't be interrupted during bean instantiation.

I will follow up

**Comment by pivovarit** [comment] 2020-07-14 05:14
I opened up an issue in the main Quarkus repository: https://github.com/quarkusio/quarkus/issues/10709

Closing this one for now

**Closed by pivovarit** 2020-07-14 05:14 UTC
Labels: bug
