### ISSUE TITLE
Error: Detected a MBean server in the image heap and Quarkus 1.12.0.Final

### ISSUE THREAD

**Issue by micheljung** [hazelcast/quarkus-hazelcast-client#147] opened 2021-03-07 21:37 UTC
Seems like #79 is back.

Quarkus version: `1.12.0.Final`
quarkus-hazelcast-client: `1.1.1`
Build image: `quay.io/quarkus/centos-quarkus-maven:21.0-java11`

```
Error: Detected a MBean server in the image heap. This is currently not supported, but could be changed in the future. Management beans are registered in many global caches that would need to be cleared and properly re-built at image build time. Class of disallowed object: com.sun.jmx.mbeanserver.JmxMBeanServer  To see how this object got instantiated use --trace-object-instantiation=com.sun.jmx.mbeanserver.JmxMBeanServer. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
```

**Comment by pivovarit** [comment] 2021-03-07 22:38
Thanks for submitting. Will have a look soon. Which Hazelcast client version are you using? the one that comes with `1.1.1`?

**Comment by micheljung** [comment] 2021-03-07 23:31
Hi, I saw that your CI builds pass so I went back and tried to use the exact versions you use, without success.

I will try to reproduce the error here and will get back to you once I know more: https://gitlab.com/michel.jung89/quarkus-test

**Comment by pivovarit** [comment] 2021-03-08 06:06
Great! That would be super useful!

**Comment by micheljung** [comment] 2021-03-08 08:24
Alright, I was able to reproduce it by:

1. Download a hazelcast-enabled project from Quarkus
2. Add a multistage-build Dockerfile
3. Configure a HazelcastInstance

See https://gitlab.com/michel.jung89/quarkus-test.git

Output:
```
Running with gitlab-runner 13.9.0 (2ebc4dc4)
  on mj-gitlab-runner JD_BD1h7
section_start:1615189083:prepare_executor
Preparing the "docker" executor
Using Docker executor with image docker:latest ...
Starting service docker:dind ...
Pulling docker image docker:dind ...
Using docker image sha256:6e82c575b16fb92f31c77a6ba88cadffa1720acd6e33526d82814232a82eb780 for docker:dind with digest docker@sha256:9f9a930bc5ec2e000867a87de844cae04590bafe929340e2fae4cb959cf6bc8f ...
Waiting for services to be up and running...
Pulling docker image docker:latest ...
Using docker image sha256:726d1128eadb7fcf512b13eeee08dccd07713749b6e619ac81a2a0233d04c7bb for docker:latest with digest docker@sha256:584001a955e828310dec75bd4e82afae406f14a37963f100efc12c651f319dd3 ...
section_end:1615189093:prepare_executor
section_start:1615189093:prepare_script
Preparing environment
Running on runner-jdbd1h7-project-24954091-concurrent-0 via gitlab-runner...
section_end:1615189094:prepare_script
section_start:1615189094:get_sources
Getting source from Git repository
Fetching changes with git depth set to 50...
Reinitialized existing Git repository in /builds/mj-treasure-hunter/quarkus-test/.git/
Checking out 540688f2 as main...

Skipping Git submodules setup
section_end:1615189096:get_sources
section_start:1615189096:step_script
Executing "step_script" stage of the job script
Using docker image sha256:726d1128eadb7fcf512b13eeee08dccd07713749b6e619ac81a2a0233d04c7bb for docker:latest with digest docker@sha256:584001a955e828310dec75bd4e82afae406f14a37963f100efc12c651f319dd3 ...
$ docker build --progress=plain -f src/main/docker/Dockerfile.multistage .
Sending build context to Docker daemon  280.6kB

Step 1/15 : FROM quay.io/quarkus/centos-quarkus-maven:21.0-java11 AS build
21.0-java11: Pulling from quarkus/centos-quarkus-maven
7a0437f04f83: Pulling fs layer
eeb2a315ca4d: Pulling fs layer
7a0437f04f83: Verifying Checksum
7a0437f04f83: Download complete
7a0437f04f83: Pull complete
eeb2a315ca4d: Verifying Checksum
eeb2a315ca4d: Download complete
eeb2a315ca4d: Pull complete
Digest: sha256:77ec910b8c1b4934b441c795222f7ff42231c73faedfec8d91e4f37200cc6185
Status: Downloaded newer image for quay.io/quarkus/centos-quarkus-maven:21.0-java11
 ---> 1f23d98b1c22
Step 2/15 : COPY src /usr/src/app/src/
 ---> d981f0d32ccb
Step 3/15 : COPY build.gradle.kts /usr/src/app/
 ---> 5d82d68a78d1
Step 4/15 : COPY settings.gradle.kts /usr/src/app/
 ---> cc2f1f084058
Step 5/15 : COPY gradle.properties /usr/src/app/
 ---> d2e02ce9adf5
Step 6/15 : USER root
 ---> Running in 34c1174bcd56
Removing intermediate container 34c1174bcd56
 ---> a022b3e79f48
Step 7/15 : RUN chown -R quarkus /usr/src/app
 ---> Running in aaaf8f2c65a3
Removing intermediate container aaaf8f2c65a3
 ---> cfe2797de162
Step 8/15 : USER quarkus
 ---> Running in 0eb18c9ab683
Removing intermediate container 0eb18c9ab683
 ---> cf8859734425
Step 9/15 : RUN gradle -b /usr/src/app/build.gradle.kts clean buildNative
 ---> Running in a006b3ff1e92

Welcome to Gradle 6.3!

Here are the highlights of this release:
 - Java 14 support
 - Improved error messages for unexpected failures

For more details see https://docs.gradle.org/6.3/release-notes.html

To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.3/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
> Task :clean UP-TO-DATE

> Task :buildNative
The 'buildNative' task has been deprecated in favor of 'build -Dquarkus.package.type=native'

> Task :quarkusGenerateCode
preparing quarkus application

> Task :compileJava
> Task :processResources
> Task :classes
> Task :jar

> Task :quarkusBuild
building quarkus jar

[code-with-quarkus-1.0.0-SNAPSHOT-runner:221]    classlist:   3,478.70 ms,  1.19 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:221]        (cap):     531.77 ms,  1.19 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:221]        setup:   1,971.13 ms,  1.19 GB
07:40:20,210 WARNING [com.haz.ins.imp.HazelcastInstanceFactory] Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
07:40:44,580 INFO  [org.jbo.threads] JBoss Threads version 3.2.0.Final
[code-with-quarkus-1.0.0-SNAPSHOT-runner:221]     (clinit):   1,276.27 ms,  4.69 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:221]   (typeflow):  34,171.93 ms,  4.69 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:221]    (objects):  30,935.75 ms,  4.69 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:221]   (features):   1,301.54 ms,  4.69 GB
Error: Unsupported features in 3 methods
Detailed message:
Error: Detected a MBean server in the image heap. This is currently not supported, but could be changed in the future. Management beans are registered in many global caches that would need to be cleared and properly re-built at image build time. Class of disallowed object: com.sun.jmx.mbeanserver.JmxMBeanServer  To see how this object got instantiated use --trace-object-instantiation=com.sun.jmx.mbeanserver.JmxMBeanServer. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
	indexing into array
		constant java.lang.Object[]@4120b829 reached by 
	reading field java.util.ArrayList.elementData of
		constant java.util.ArrayList@4e140b82 reached by [code-with-quarkus-1.0.0-SNAPSHOT-runner:221]     analysis:  70,887.12 ms,  4.69 GB

	scanning method javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
Call path from entry point to javax.management.MBeanServerFactory.addMBeanServer(MBeanServer): 
	at javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:232)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:250)
	at com.oracle.svm.core.jdk.management.Target_java_lang_management_ManagementFactory.getPlatformMBeanServer(Target_java_lang_management_ManagementFactory.java:45)
	at com.hazelcast.internal.jmx.ManagementService.shutdown(ManagementService.java:118)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.remove(HazelcastInstanceFactory.java:313)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:103)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:84)
	at com.hazelcast.instance.impl.Node$NodeShutdownHookThread.run(Node.java:752)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
	at parsing com.hazelcast.internal.usercodedeployment.impl.ClassSource.define(ClassSource.java:52)
Call path from entry point to com.hazelcast.internal.usercodedeployment.impl.ClassSource.define(String, byte[]): 
	at com.hazelcast.internal.usercodedeployment.impl.ClassSource.define(ClassSource.java:52)
	at com.hazelcast.internal.usercodedeployment.impl.ClassLocator.defineClassFromClient(ClassLocator.java:135)
	at com.hazelcast.internal.usercodedeployment.impl.ClassLocator.defineClassesFromClient(ClassLocator.java:107)
	at com.hazelcast.internal.usercodedeployment.UserCodeDeploymentService.defineClasses(UserCodeDeploymentService.java:74)
	at com.hazelcast.internal.usercodedeployment.impl.operation.DeployClassesOperation.run(DeployClassesOperation.java:52)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:160)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:138)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:123)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: type is not available in this platform: org.graalvm.compiler.hotspot.management.AggregatedMemoryPoolBean
Trace: Object was reached by 
	reading field java.lang.ref.Reference.referent of
		constant java.util.WeakHashMap$Entry@782ccee4 reached by 
	indexing into array
		constant java.util.WeakHashMap$Entry[]@20ce28f0 reached by 
	reading field java.util.WeakHashMap.table of
		constant com.sun.jmx.mbeanserver.MBeanIntrospector$MBeanInfoMap@69c027bd reached by 
	scanning method com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
Call path from entry point to com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(): 
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getClassMBeanInfo(MBeanIntrospector.java:416)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getMBeanInfo(MBeanIntrospector.java:392)
	at com.sun.jmx.mbeanserver.MBeanSupport.<init>(MBeanSupport.java:139)
	at com.sun.jmx.mbeanserver.MXBeanSupport.<init>(MXBeanSupport.java:66)
	at com.sun.jmx.mbeanserver.Introspector.makeDynamicMBean(Introspector.java:203)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:888)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
	at com.sun.jmx.mbeanserver.JmxMBeanServer$2.run(JmxMBeanServer.java:1225)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:120)
	at java.net.Socket.getOutputStream(Socket.java:969)
	at org.jboss.logmanager.handlers.TcpOutputStream.flush(TcpOutputStream.java:214)
	at java.io.PrintStream.flush(PrintStream.java:417)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

com.oracle.svm.core.util.UserError$UserException: Unsupported features in 3 methods
Detailed message:
Error: Detected a MBean server in the image heap. This is currently not supported, but could be changed in the future. Management beans are registered in many global caches that would need to be cleared and properly re-built at image build time. Class of disallowed object: com.sun.jmx.mbeanserver.JmxMBeanServer  To see how this object got instantiated use --trace-object-instantiation=com.sun.jmx.mbeanserver.JmxMBeanServer. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
	indexing into array
		constant java.lang.Object[]@4120b829 reached by 
	reading field java.util.ArrayList.elementData of
		constant java.util.ArrayList@4e140b82 reached by 
	scanning method javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
Call path from entry point to javax.management.MBeanServerFactory.addMBeanServer(MBeanServer): 
	at javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:232)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:250)
	at com.oracle.svm.core.jdk.management.Target_java_lang_management_ManagementFactory.getPlatformMBeanServer(Target_java_lang_management_ManagementFactory.java:45)
	at com.hazelcast.internal.jmx.ManagementService.shutdown(ManagementService.java:118)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.remove(HazelcastInstanceFactory.java:313)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:103)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:84)
	at com.hazelcast.instance.impl.Node$NodeShutdownHookThread.run(Node.java:752)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
	at parsing com.hazelcast.internal.usercodedeployment.impl.ClassSource.define(ClassSource.java:52)
Call path from entry point to com.hazelcast.internal.usercodedeployment.impl.ClassSource.define(String, byte[]): 
	at com.hazelcast.internal.usercodedeployment.impl.ClassSource.define(ClassSource.java:52)
	at com.hazelcast.internal.usercodedeployment.impl.ClassLocator.defineClassFromClient(ClassLocator.java:135)
	at com.hazelcast.internal.usercodedeployment.impl.ClassLocator.defineClassesFromClient(ClassLocator.java:107)
	at com.hazelcast.internal.usercodedeployment.UserCodeDeploymentService.defineClasses(UserCodeDeploymentService.java:74)
	at com.hazelcast.internal.usercodedeployment.impl.operation.DeployClassesOperation.run(DeployClassesOperation.java:52)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:160)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:138)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:123)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: type is not available in this platform: org.graalvm.compiler.hotspot.management.AggregatedMemoryPoolBean
Trace: Object was reached by 
	reading field java.lang.ref.Reference.referent of
		constant java.util.WeakHashMap$Entry@782ccee4 reached by 
	indexing into array
		constant java.util.WeakHashMap$Entry[]@20ce28f0 reached by 
	reading field java.util.WeakHashMap.table of
		constant com.sun.jmx.mbeanserver.MBeanIntrospector$MBeanInfoMap@69c027bd reached by 
	scanning method com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
Call path from entry point to com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(): 
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getClassMBeanInfo(MBeanIntrospector.java:416)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getMBeanInfo(MBeanIntrospector.java:392)
	at com.sun.jmx.mbeanserver.MBeanSupport.<init>(MBeanSupport.java:139)
	at com.sun.jmx.mbeanserver.MXBeanSupport.<init>(MXBeanSupport.java:66)
	at com.sun.jmx.mbeanserver.Introspector.makeDynamicMBean(Introspector.java:203)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:888)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
	at com.sun.jmx.mbeanserver.JmxMBeanServer$2.run(JmxMBeanServer.java:1225)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:120)
	at java.net.Socket.getOutputStream(Socket.java:969)
	at org.jboss.logmanager.handlers.TcpOutputStream.flush(TcpOutputStream.java:214)
	at java.io.PrintStream.flush(PrintStream.java:417)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:233)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:773)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 3 methods
Detailed message:
Error: Detected a MBean server in the image heap. This is currently not supported, but could be changed in the future. Management beans are registered in many global caches that would need to be cleared and properly re-built at image build time. Class of disallowed object: com.sun.jmx.mbeanserver.JmxMBeanServer  To see how this object got instantiated use --trace-object-instantiation=com.sun.jmx.mbeanserver.JmxMBeanServer. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
	indexing into array
		constant java.lang.Object[]@4120b829 reached by 
	reading field java.util.ArrayList.elementData of
		constant java.util.ArrayList@4e140b82 reached by 
	scanning method javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
Call path from entry point to javax.management.MBeanServerFactory.addMBeanServer(MBeanServer): 
	at javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:232)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:250)
	at com.oracle.svm.core.jdk.management.Target_java_lang_management_ManagementFactory.getPlatformMBeanServer(Target_java_lang_management_ManagementFactory.java:45)
	at com.hazelcast.internal.jmx.ManagementService.shutdown(ManagementService.java:118)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.remove(HazelcastInstanceFactory.java:313)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:103)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:84)
	at com.hazelcast.instance.impl.Node$NodeShutdownHookThread.run(Node.java:752)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
	at parsing com.hazelcast.internal.usercodedeployment.impl.ClassSource.define(ClassSource.java:52)
Call path from entry point to com.hazelcast.internal.usercodedeployment.impl.ClassSource.define(String, byte[]): 
	at com.hazelcast.internal.usercodedeployment.impl.ClassSource.define(ClassSource.java:52)
	at com.hazelcast.internal.usercodedeployment.impl.ClassLocator.defineClassFromClient(ClassLocator.java:135)
	at com.hazelcast.internal.usercodedeployment.impl.ClassLocator.defineClassesFromClient(ClassLocator.java:107)
	at com.hazelcast.internal.usercodedeployment.UserCodeDeploymentService.defineClasses(UserCodeDeploymentService.java:74)
	at com.hazelcast.internal.usercodedeployment.impl.operation.DeployClassesOperation.run(DeployClassesOperation.java:52)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:160)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:138)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:123)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: type is not available in this platform: org.graalvm.compiler.hotspot.management.AggregatedMemoryPoolBean
Trace: Object was reached by 
	reading field java.lang.ref.Reference.referent of
		constant java.util.WeakHashMap$Entry@782ccee4 reached by 
	indexing into array
		constant java.util.WeakHashMap$Entry[]@20ce28f0 reached by 
	reading field java.util.WeakHashMap.table of
		constant com.sun.jmx.mbeanserver.MBeanIntrospector$MBeanInfoMap@69c027bd reached by 
	scanning method com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
Call path from entry point to com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(): 
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getClassMBeanInfo(MBeanIntrospector.java:416)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getMBeanInfo(MBeanIntrospector.java:392)
	at com.sun.jmx.mbeanserver.MBeanSupport.<init>(MBeanSupport.java:139)
	at com.sun.jmx.mbeanserver.MXBeanSupport.<init>(MXBeanSupport.java:66)
	at com.sun.jmx.mbeanserver.Introspector.makeDynamicMBean(Introspector.java:203)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:888)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
	at com.sun.jmx.mbeanserver.JmxMBeanServer$2.run(JmxMBeanServer.java:1225)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:120)
	at java.net.Socket.getOutputStream(Socket.java:969)
	at org.jboss.logmanager.handlers.TcpOutputStream.flush(TcpOutputStream.java:214)
	at java.io.PrintStream.flush(PrintStream.java:417)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:770)
	... 8 more
Error: Image build request failed with exit status 1

> Task :quarkusBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
  	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
  	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:281)
7 actionable tasks: 6 executed, 1 up-to-date
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
  	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
  	at java.base/java.lang.Thread.run(Thread.java:834)
  	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 1
  	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:443)
  	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:253)
  	... 10 more


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 1s
The command '/bin/sh -c gradle -b /usr/src/app/build.gradle.kts clean buildNative' returned a non-zero code: 1
section_end:1615189286:step_script
section_start:1615189286:cleanup_file_variables
Cleaning up file based variables
section_end:1615189287:cleanup_file_variables
ERROR: Job failed: exit code 1
```

**Comment by pivovarit** [comment] 2021-03-08 15:45
Managed to reproduce it! Still, no clue why it's not showing up during standard testing :)

**Comment by pivovarit** [comment] 2021-03-08 15:57
Ok, I found the problem.

The issue is that you're actually trying to wire-up an embedded Hazelcast instance instead of a client. Embedded Hazelcast is not supported (notice the name of the artifact `com.hazelcast:quarkus-hazelcast-client`).

Also, there's no need to wire-up your own `HazelcastInstance` on your own, the classpath presence of the extension triggers the autoconfiguration!

If that's all that was needed here, please close the issue

**Closed** 2021-03-08 17:25 UTC
Labels: bug

**Comment by pivovarit** [comment] 2021-03-08 18:58
No worries, you're welcome :)
